# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
## Custom notifications
Notify:
  Webhooks:
    # A list of hook hashes, containing the url file
    - url: https://dslzuha.webhook.office.com/webhookb2/1f31151d-e343-4c13-b0c2-cdf99319b092@202b3f81-76fa-4f2d-bf49-9d9bea15fa6e/CircleCI/e003fc97c83c4e6b81a49b2804decbfe/f17bfd43-6c0a-43cc-b80e-bfa2dad3e95a
    
